name: 'auto_sign_smzdm'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '3 2 * * *'

jobs:
  smzdm_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests

      - name: 'smzdm_sign'
        run: python run.py smzdm
        env:
          SMZDM_COOKIES: ${{ secrets.SMZDM_COOKIES }}
          QMSGAPI: ${{ secrets.QMSGAPI }}
